### ISSUE TITLE
Bug: Mux video not working in TikTok browser

### ISSUE THREAD

**Issue by mrtil35** [muxinc/elements#343]
### Checklist
- [X] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-video
- mux-audio

### Which browser(s) are you using?
TikTok in-app browser (uses Safari iOS)

### Which operating system(s) are you using?
iOS

### Describe the bug
TikTok uses custom JS in their browser, but other video players have figured out workarounds to make playback work. Mux isn't loading though when a link with a Mux video is loaded from the TikTok browser. This creates a broken user experience.

## Steps To Reproduce

1. Take any website with a Mux video on the page
2. Create a TikTok account (make it a business type so you can add a link-in-bio)
3. Tap the link-in-bio and see that the video does not load/play

## The current behavior
Video does not play, even when auto-play is disabled

## The expected behavior
Video should have a way to play, other video players seem to work just fine

**Comment by dylanjha** [comment]
@mrtil35 thanks for the bug report. In-app browsers are notoriously difficult to debug because I don't know of a way to attach a debugger or access a developer console.

I tried creating a business type account and added link in bio but it's not clickable in the bio. This is definitely a business account because on settings I can see the option to switch back to personal.

Maybe because it's a new account I have some restrictions? Do you have a test profile with a clickable link to a page with Mux Player?

![IMG_3349](https://user-images.githubusercontent.com/764988/186527167-21702869-c660-4d10-8c00-21830cbee7e7.jpg)
![IMG_3350](https://user-images.githubusercontent.com/764988/186527163-77ab0e7e-6934-4857-9366-b29bb947bc9c.jpg)

In your case does the player render and just not play? Or does the player not render at all? Can you attach a screenshot of what you see?

Better yet, could you follow [the instructions here](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#examples) to set up a listener on the window `error` event and write the error logs to the DOM?

I think that would be the only way to get some visibility into the errors in the in-app browser.

**Comment by mrtil35** [comment]
Hey @dylanjha thanks for the quick response. Try tapping the link in bio here, that's a video that will play on IG browser, Safari iOS, etc.

https://www.tiktok.com/@makeitpastjanuary

**Comment by rodolphoasb** [comment]
> @mrtil35 thanks for the bug report. In-app browsers are notoriously difficult to debug because I don't know of a way to attach a debugger or access a developer console.
> 
> I tried creating a business type account and added link in bio but it's not clickable in the bio. This is definitely a business account because on settings I can see the option to switch back to personal.
> 
> Maybe because it's a new account I have some restrictions? Do you have a test profile with a clickable link to a page with Mux Player?
> 
> ![IMG_3349](https://user-images.githubusercontent.com/764988/186527167-21702869-c660-4d10-8c00-21830cbee7e7.jpg) ![IMG_3350](https://user-images.githubusercontent.com/764988/186527163-77ab0e7e-6934-4857-9366-b29bb947bc9c.jpg)
> 
> In your case does the player render and just not play? Or does the player not render at all? Can you attach a screenshot of what you see?
> 
> Better yet, could you follow [the instructions here](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#examples) to set up a listener on the window `error` event and write the error logs to the DOM?
> 
> I think that would be the only way to get some visibility into the errors in the in-app browser.

Hey, @dylanjha! 

I'll try this!

I made a test profile and in this profile, we have more than 1000 followers, which is the requirement to put a clickable link in the bio. I have a Linktree there, if you want to I can add your ngrok link there (I'm using this to debug).

**Comment by dylanjha** [comment]
Got it

I can see the video plays in Safari iOS https://www.learnontil.com/class/jude-smith-teaches-music-production-mixing-for-beginners

... but, as you reported it does not play in the TikTok in-app browser 👎🏼 

This feels a lot like an autoplay issue and I see this video has the `autoplay` attribute. You said you tried removing that?

**Comment by dylanjha** [comment]
Next debugging step, if you could try removing the `autoplay` attribute and doing something like:

```html
<script>
  const video = document.querySelector('#videoBox video');
  video.play().then(() => {
      // write "video played" somewhere you can see in the DOM
  }).catch((err) => {
      // write "error playing video" somewhere you can see in the DOM
  });
</script>
```

**Comment by rodolphoasb** [comment]
Hey, @dylanjha!

Thanks for your help! I think we can close this now!

What I end up doing to make this work:

```
const [browser, setBrowser] = useState('');

  useEffect(() => {
    setBrowser(navigator.userAgent);
  }, []);

  const isTikTokDisableAutoPlay = browser.includes('BytedanceWebview');
```

If isTikTokDisableAutoPlay is true, I render another version of `video` without the autoplay attribute.

**Comment by dylanjha** [comment]
Glad you found a workaround @rodolphoasb! Thanks for the follow-up.

Instead of special-casing the tiktok browser, I would avoid the default `autoplay` attribute and try to play the video programmatically:

```js
const video = document.querySelector('#my-video');

video.play().then(function () {
  // autoplay was successful!
}).catch(function (error) {
  // do something if you want to handle or track this error
}); 
```

Here's a guide with more info about autoplay attribute: https://docs.mux.com/guides/video/web-autoplay-your-videos
