### ISSUE TITLE
Bug: player not working

### ISSUE THREAD

**Issue by ankuragrawal29** [muxinc/elements#499]
### Checklist

- [] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
- mux-video

### Which browser(s) are you using?
- compile error

### Which operating system(s) are you using?
Window

(For example: macOS, Windows, iOS, Android)

### How are you using Mux Elements?
 "@mux/mux-video-react": "^0.5.1",

(For example: npm package, `<script>` tag)

### Describe the bug
./node_modules/@mux/mux-video-react/dist/index.mjs
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by dylanjha** [comment]
@ankuragrawal29 thanks for opening the issue. We'll need some more details in order to help.

Doing some googling based on that error message "Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)" I found a this which might be related:

- https://stackoverflow.com/questions/69343038/cant-import-the-named-export-xxxx-from-non-ecmascript-module-only-default-expo

Since `useEffect` comes from React, I think the issue you're running into has to do with your current React version, or your webpack config

**Comment by luwes** [comment]
closing as this seems to be a React build issue.

our demo apps are building ok
https://elements-demo-create-react-ljge6oqbm-mux.vercel.app/#/MuxVideo
