### ISSUE TITLE
Bug: Controls are block from video

### ISSUE THREAD

**Issue by jackguoAtJogg** [muxinc/elements#644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player, mux-player-react

### Which browsers are you using?

Safari

### Which operating systems are you using?

macOS

### Description

The video would block control section while the video is playing on safari.

Safari version: 16.3

### Steps to reproduce

1. Open safari
2. Go to https://staging.watch.jogg.co/r/4G0d
3. Play video and hover over

### Current Behavior

The control is hidden from video

### Expected Behavior

The control shows in the front

**Comment by luwes** [comment]
thanks for the feedback! this looks like a browser bug and it looks like it is caused by some CSS in your page.

I reproduced it here and commenting out the `position: fixed` resolved the issue in Safari.
https://codesandbox.io/s/mux-player-safari-controlbar-bug-wkexh3?file=/index.html

Hope this helps, there's nothing we can change in Mux player to improve this behavior in Safari.

**Comment by jackguoAtJogg** [comment]
I see, thank you for the help!!
