### ISSUE TITLE
Bug: poster image

### ISSUE THREAD

**Issue by jackguoAtJogg** [muxinc/elements#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player, mux-player-react

### Which browsers are you using?

Chrome, Safari, Firefox

### Which operating systems are you using?

macOS

### Description

The poster doesn't have a black background when the poster is not 16:9 ratio, my fix for this issue is to add poster attribute to the video element.

### Steps to reproduce

1. https://codesandbox.io/s/mux-player-safari-controlbar-bug-forked-gxl5qe?file=/index.html

### Current Behavior

The non 16:9 ratio poster show in front of video.

### Expected Behavior

There should be a black background behind non 16:9 ratio.

**Comment by luwes** [comment]
thanks for the question. this is expected behavior. it's possible to solve in a few ways:
- setting preload=none which wouldn't load the video in the background until the user plays https://codesandbox.io/s/mux-player-safari-controlbar-bug-preload-none-2kcrlq
- using the CSS poster part to add a background color to the poster image element https://codesandbox.io/s/mux-player-safari-controlbar-bug-poster-part-rqd6b7
- stretching out the poster so it covers the whole player https://codesandbox.io/s/mux-player-safari-controlbar-bug-media-object-fit-cu1cwb?file=/index.html

hope this helps cheers!
