### ISSUE TITLE
DOM property to attribute reflection

### ISSUE THREAD

**Issue by luwes** [muxinc/elements#66]
Noticed this today, native HTML element's string properties that receive a `null` or `undefined` are cast as string and still set as a string to the attribute. The Mux elements behave differently as seen below, removing the attribute. 

https://github.com/muxinc/elements/blob/675fc314751b667e29c25d621bb08cadc5585f58/packages/mux-video/src/index.ts#L97-L107

**Comment by cjpillsbury** [comment]
This was intentional, but maybe it shouldn't have been. To be consistent, it looks like we'd need to rely on `src = ''`. Would need to smoke test to see if there are any "ripple effects"/assumptions elsewhere, including playback-core, but I'm amenable to the refactor. This feels like it's part of the larger conversation of "should `<mux-video/>` be as close as possible to the API/behaviors of `<video/>`, or should we diverge ever?"
