### ISSUE TITLE
Bug: chosen streamtype incorrect

### ISSUE THREAD

**Issue by luwes** [muxinc/elements#667]
stumbled on a bug in v1.10.0 where the live UI is rendered for a on-demand video.

https://dev.playerx.io/demo/mux/2/

**Comment by dylanjha** [comment]
Good catch 👍🏼

**Comment by cjpillsbury** [comment]
Hey @luwes this is actually the current intended behavior for derived stream type. In order to avoid mid-playback UI switching, we differentiate between an "live but ended" media playlist vs. an "on demand" playlist. Per the HLS spec/RFC 8216, an on demand playlist should have an `#EXT-X-PLAYLIST-TYPE:VOD` tag (See: https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-12#section-4.4.3.5). In the example playlist on the page, the media playlists are effectively "ended but live" - i.e., they have no `#EXT-X-PLAYLIST-TYPE` tag. Example:

```
# NOTE: no EXT-X-PLAYLIST-TYPE tag
#EXTM3U

#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:4

#EXTINF:4.0
../video/180_250000/hls/segment_0.ts
# ... more EXTINF tags
#EXT-X-ENDLIST
```

**Comment by luwes** [comment]
ah gotcha! 👍
