### ISSUE TITLE
Bug: Timeline disappears while scrubbing on mobile.

### ISSUE THREAD

**Issue by theazgra** [muxinc/elements#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player

### Which browsers are you using?

Chrome, Edge ("Edgeium")

### Which operating systems are you using?

Android

### Description

Hi,

We are dealing with this weird behaviour, that timeline with all controls dissapper on mobile while scrubbing. I don't think that this is desired? 

https://github.com/muxinc/elements/assets/18343952/4a7200b6-807b-430d-aa49-b08f270b1461

### Reduced test case

https://docs.mux.com/guides/player

### Steps to reproduce

1. Play video
2. Scrub on timeline
3. Timeline with all acontrols dissapperas

### Current Behavior

Timeline with all acontrols dissapperas

### Expected Behavior

Timeline with all acontrols stays visible while scrubbing

### What version of the package are you using?

1.11.2

**Comment by cjpillsbury** [comment]
Hey @theazgra thanks for the feedback! I agree this user experience is a bit awkward, but it is the current expected behavior based on how [Media Chrome](https://github.com/muxinc/media-chrome) works, which is what Mux Player uses for its UI "under the hood." If you don't mind creating a new proposal in Media Chrome (https://github.com/muxinc/media-chrome/discussions/new?category=proposals) and linking this issue, that would better ensure its visibility for the team.

**Comment by luwes** [comment]
this should be fixed in v2.2.0!
