### ISSUE TITLE
Bug: website elements above fullscreen video

### ISSUE THREAD

**Issue by CanRau** [muxinc/elements#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

- mux-video
- mux-video-react

### Which browsers are you using?

Safari on iOS

### Which operating systems are you using?

iOS

### Description

My colleague just showed me this screenshot from Safari on his iPad, sadly I can't reproduce it myself on my iPad, or any other device, he also said that on other devices it works as expected.

So the website elements, Logo, the whole navigation at top, the five circular avatars almost in the center are not supposed to be above the video. How can I ensure this doesn't happen? The 

![image](https://github.com/muxinc/elements/assets/5196971/1e26bca6-8f97-46c7-a185-663ccf8197ea)

The video is on this page https://www.konduktum.com/k/nIhvyp72xozgu

### Steps to reproduce

As mentioned I can't reproduce, though it just happens when entering fullscreen on his iPad's Safari, he's got the M1 Pro on IpadOS 16.2

### Current Behavior

website elements, top navigation and avatars are showing above the video

### Expected Behavior

fullscreen video should cover everything else and not allow anything to be on top

### What version of the package are you using?

1.11.4

**Comment by cjpillsbury** [comment]
Hey @CanRau also having trouble reproducing. My suspicion is it's a bug in WebKit/Safari related to "correct" vs. actual z-indexing. Not sure how viable this is, but could you try explicitly bumping up the z-index on `mux-player` to higher than the value applied to the other elements on the page using a >0 z-index?

Also, if you could confirm whether or not your colleague is on the latest version of iPadOS/Safari, that would be helpful.

Tangentially related: Since this is an issue with `mux-player`/`mux-player-react`, would you mind updating "Which Mux Elements/Packages does this apply to? Select all that apply" to one of those so we can better track the issue?

**Comment by luwes** [comment]
related issue https://github.com/muxinc/elements/issues/644

Safari is very sensitive to this stuff. The best way to find out what is causing this is removing all CSS styles in the page which should fix the bug. Then step by step add CSS blocks until it breaks, and then precisely find the CSS property that adds this glitch.

**Comment by CanRau** [comment]
Hey thank you for your comments, still didn't have the time to look into this again, probably next week get the time.
I'll keep you posted

**Comment by CanRau** [comment]
Adding a high z-index solved it 🥳 finally had the time 😅
closing then, thanks y'all
