### ISSUE TITLE
Bug: mux-uploader 'success' immediately triggered when selecting file in Safari

### ISSUE THREAD

**Issue by cgs** [muxinc/elements#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-uploader

### Which browsers are you using?

Safari

### Which operating systems are you using?

macOS

### Description

Using mux-uploader. I have a 4.5 GB .mov file that when selected via the file browser (or using drag/drop) immediately triggers the 'success' event and the file is not actually uploaded:

https://github.com/muxinc/elements/assets/16057/f123ef43-0449-4a31-8dc1-a6cedc20f51e

This only happens with this specific file and in Safari. There are no errors in the console. It works ok in Chrome. Here are the video specs:

![Original-File](https://github.com/muxinc/elements/assets/16057/5fa680e9-7c1a-4ca4-addb-646b9a0e8cc4)

Here is the video file: https://www.dropbox.com/scl/fo/a3abqnobqroiaomuv1u1r/h?preview=Daily+Meditation_v2.mov&rlkey=w39tdtitdux7thftzpxjd6od3&dl=0

### Steps to reproduce

1. Download the file linked above
2. In a bare-bones mux-uploader implementation, drag or select the file in Safari

### Current Behavior

'success' immediately triggered and "Upload Complete" shown, but file not actually uploaded. See video above

### Expected Behavior

File should upload normally

### Errors

There are no console errors.

### What version of the package are you using?

1.0.0-beta.15

**Comment by cjpillsbury** [comment]
Hey @cgs sorry for the slow response! This is is sadly due to a bug in WebKit (https://bugs.webkit.org/show_bug.cgi?id=272600). We're hoping to eventually implement an "opt in" (sub-optimal) fallback, but in the interim, I've made some updates to at least appropriately notify the state with some default guidance for the user. Given the browser-based nature of this bug, do you think this will hold you over for your use case until either WebKit fixes it or we get that "less than ideal" workaround in place?
<img width="897" alt="Screenshot 2024-04-18 at 3 02 16 PM" src="https://github.com/muxinc/elements/assets/2389566/87297607-ccb5-4569-8ac5-5841aa2d159f">

**Comment by cjpillsbury** [comment]
A couple of updates here:
1. `mux-uploader` and `mux-uploader-react` now support an optional `use-large-file-workaround` attribute / `useLargeFileWorkaround` prop to use a less memory efficient method "under the hood" for loading and chunking files. The latest canary should have this and we're planning on doing an official release soon.
2. It looks like the very latest version of Safari has **_finally_** resolved the bug referenced above, so if folks are completely up to date, the fallback may not be used/necessary.
